### ISSUE TITLE
Issues with Emacs 30

### ISSUE THREAD

**Issue by fosskers** [justinbarclay/parinfer-rust-mode#110]
Hi there, since switching to Emacs 30 I've started having issues. 

### Flycheck

Flycheck seems displeased with: https://github.com/justinbarclay/parinfer-rust-mode/blob/main/parinfer-rust-flycheck.el#L35

Citing this the first time I open a Lisp buffer:
```
Error while checking syntax automatically: (void-variable parinfer-rust--error)
```

### General Function

Otherwise, even after having reinstalled this mode completely and redownloading the `.so`, I don't observe it to actually be managing parentheses. Particularly jarring is when I delete a line with many trailing parens, and those parens don't "warp" up to the next line as usual.

Any ideas? Thank you.

**Comment by nstgc** [comment]
> Otherwise, even after having reinstalled this mode completely and redownloading the .so, I don't observe it to actually be managing parentheses. Particularly jarring is when I delete a line with many trailing parens, and those parens don't "warp" up to the next line as usual.

I've been seeing this exact behavior for approximately two weeks, but with Emacs 29.4. For me, it isn't 100%, but it's close. Sometimes I can get it to work if I toggle the mode off and on enough times.

**Comment by fosskers** [comment]
As mentioned in the linked issue, the issue is with the `track-changes` library, which is doing naughty things upstream w.r.t. `incf` vs `cl-incf`. For anyone who wanders in here, apply the patch [linked here](https://github.com/doomemacs/doomemacs/issues/8295#issuecomment-2692889405) within your local clone of `track-changes`.

**Comment by justinbarclay** [comment]
@fosskers thanks for pointing out the void-variable issue and looking into the track-changes library issue.

Unfortunately, because you're using `straight`, I'm not sure I can do much to resolve any issues there. So, I think until track-changes fixes it upstream, you're stuck with your patch.

However, I have merged a small [PR](https://github.com/justinbarclay/parinfer-rust-mode/pull/111) to hopefully fix your `void-variable` issue

**Comment by fosskers** [comment]
Thank you! Upstream also recently solved a similar issues involving `incf` in another place, but they may not know it's broken in `track-changes` too. I will confirm that soon.

**Comment by samuelludwig** [comment]
I'm personally still experiencing this on 29.4 (with the `track-changes` patch, which I'm assuming/hoping I've applied correctly)

**Comment by justinbarclay** [comment]
> I'm personally still experiencing this on 29.4 (with the `track-changes` patch, which I'm assuming/hoping I've applied correctly)
> 
> Post-Stamp: it appears that parinfer works after i disable and then re-enable it in a session

I'm using normal package.el, I don't run into this issue and therefore I'm not sure what advice I can offer.

 However, if I had to guess, this works after you re-enable parinfer in a session because you apply this sometime after parinfer loads? I think parinfer-rust-mode is crashing for you because the function definitions are still incorrect when it first runs. Therefore, I think for the patch to work seemlessly, you have to load `track-changes.el` and apply the necessary patch before `parinfer-rust-mode.el` loads.

**Comment by fosskers** [comment]
This seems to have been finally fixed upstream.
